In [85]:
import gmaps
import numpy as np

gmaps.configure(api_key="AIzaSyApj3xGPGx1naRs2DZiUlJ6moRftzWzTJU")
party = pd.read_csv('party_in_nyc.csv', usecols=('Latitude', 'Longitude'))
print(np.array(party).astype(float))
fig = gmaps.figure()
fig.add_layer(gmaps.heatmap_layer(np.array(party).astype(float)))
fig

[[ 40.86618344 -73.91893043]
 [ 40.85932419 -73.93123734]
 [ 40.79941541 -73.95337117]
 ..., 
 [ 40.74366173 -73.92306726]
 [ 40.85844745 -73.92927889]
 [ 40.87744967 -73.91049846]]


InvalidPointException: nan is not a valid latitude. Latitudes must lie between -90 and 90.

In [61]:
import pandas as pd

party = pd.read_csv('party_in_nyc.csv', usecols=('Latitude', 'Longitude'))
print(np.array(party))
latitude = np.array(party['Latitude'])
longitude = np.array(party['Longitude'])

print(np.hstack((latitude,longitude)))

np.array(party['Latitude'], party['Longitude']).T

[[ 40.86618344 -73.91893043]
 [ 40.85932419 -73.93123734]
 [ 40.79941541 -73.95337117]
 ..., 
 [ 40.74366173 -73.92306726]
 [ 40.85844745 -73.92927889]
 [ 40.87744967 -73.91049846]]
[ 40.86618344  40.85932419  40.79941541 ..., -73.92306726 -73.92927889
 -73.91049846]


array([ 40.86618344,  40.85932419,  40.79941541, ...,  40.74366173,
        40.85844745,  40.87744967])

In [ ]:

data = np.loadtxt('party_in_nyc.csv', dtype='float', delimiter=',', skiprows=1, usecols=range(6, 7))